name: ai_glow
description: "ai_glow — Flutter widgets that add animated, customizable inner and outer glow effects (InnerAiGlowing, OuterAiGlow). Lightweight and easy to style: colors, blur, glowWidth, borderRadius, and size."
version: 0.0.3
homepage: https://github.com/ahmeddouss/ai_glow.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
